<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Assertion passed: LOGIN Page title is same as expected]]>
    </line>
    <line>
      <![CDATA[user entered user id as xyz@abc.con]]>
    </line>
    <line>
      <![CDATA[user enterd password]]>
    </line>
    <line>
      <![CDATA[User clicked on login button]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="12812" started-at="2016-05-10T13:42:55Z" finished-at="2016-05-10T13:43:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12812" started-at="2016-05-10T13:42:55Z" finished-at="2016-05-10T13:43:08Z">
      <class name="com.UnitellerAutomation.Tests.Uniteller_UserLogin">
        <test-method status="PASS" signature="loadTestData()[pri:0, instance:com.UnitellerAutomation.Tests.Uniteller_UserLogin@383bfa16]" name="loadTestData" is-config="true" duration-ms="5" started-at="2016-05-10T06:42:55Z" finished-at="2016-05-10T06:42:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadTestData -->
        <test-method status="FAIL" signature="Step_01_LaunchApplication()[pri:0, instance:com.UnitellerAutomation.Tests.Uniteller_UserLogin@383bfa16]" name="Step_01_LaunchApplication" duration-ms="12796" started-at="2016-05-10T06:42:55Z" finished-at="2016-05-10T06:43:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Assertion Failed]: Error Message is not as expected expected [Invalid login Attempt. Please provide valid credentials to prevent your login from being loc] but found [Invalid login Attempt. Please provide valid credentials to prevent your login from being locked.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Assertion Failed]: Error Message is not as expected expected [Invalid login Attempt. Please provide valid credentials to prevent your login from being loc] but found [Invalid login Attempt. Please provide valid credentials to prevent your login from being locked.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.UnitellerAutomation.Keywords.LogInPage.verifyFailedLogInMessage(LogInPage.java:41)
	at com.UnitellerAutomation.Tests.Uniteller_UserLogin.Step_01_LaunchApplication(Uniteller_UserLogin.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Assertion passed: LOGIN Page title is same as expected]]>
            </line>
            <line>
              <![CDATA[user entered user id as xyz@abc.con]]>
            </line>
            <line>
              <![CDATA[user enterd password]]>
            </line>
            <line>
              <![CDATA[User clicked on login button]]>
            </line>
          </reporter-output>
        </test-method> <!-- Step_01_LaunchApplication -->
      </class> <!-- com.UnitellerAutomation.Tests.Uniteller_UserLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
